### ISSUE TITLE
Version of Apache Avro supported documentation

### ISSUE THREAD

**Issue by PLeVasseur** [apache/avro-rs#59]
Hi there 👋 I've probably missed it but, is there a listing of the currently supported version of Apache Avro by avro-rs?

When I check the [docs landing page](https://avro.apache.org/docs/1.12.0/), I also don't see Rust listed here. Could you help me understand the reason for this?

Thanks for the help! ✌️

**Comment by martin-g** [comment]
0.17 has been released with 1.12.0.
Recently we extracted avro-rs to its own repository and it will be released by itself in the future.
It is still 0.x so API breaks are possible but rare!
Otherwise we try to implement all features from the spec. Please report if something is missing!

I'll add a link at https://avro.apache.org/docs/1.12.0/ that will forward to https://docs.rs/apache-avro/0.17.0/apache_avro/ !

**Comment by PLeVasseur** [comment]
Great to hear, I'll keep an eye out. Do you happen to have some rough timeline for a release to crates.io?

**Comment by martin-g** [comment]
https://crates.io/crates/apache-avro

**Comment by PLeVasseur** [comment]
D'oh! I missed this 😅 Thanks for the help :)

Closing as resolved
