### ISSUE TITLE
Incorrect PCF generation

### ISSUE THREAD

**Issue by chupaty** [apache/avro-rs#61]
Avro spec specifies the first three steps of the PCF transformation pipeline as :
[PRIMITIVES] 
[FULLNAMES]
[STRIP]

This means that the following schema fragment:
 {
      "type": {
        "logicalType": "timestamp-millis",
        "type": "long"
      },
      "name": "dt"
    },

Should transform to (leaving whitespace in):
   {
      "name": "dt",
      "type": {
        "type": "long"
      }
    },

Instead, schema::canonical_form() transforms to:
    {
      "name": "dt",
      "type": "long"
    },

I believe this is incorrect, because the PRIMITIVES transformation 'should' run before the STRIP transformation.

**Comment by martin-g** [comment]
You might be right or not ... I will have to re-read the related parts of the spec. 
It is always good to cite the sentences/paragraphs which you think are important. Otherwise we have to guess and make mistakes ...

AFAIR the produced fingerprints are the same as the ones for the Java and the Python SDKs, so you might be wrong ...
